/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FormatService } from "../format.service";
import { FormatCreateInput } from "./FormatCreateInput";
import { Format } from "./Format";
import { FormatFindManyArgs } from "./FormatFindManyArgs";
import { FormatWhereUniqueInput } from "./FormatWhereUniqueInput";
import { FormatUpdateInput } from "./FormatUpdateInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

export class FormatControllerBase {
  constructor(protected readonly service: FormatService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Format })
  async createFormat(@common.Body() data: FormatCreateInput): Promise<Format> {
    return await this.service.createFormat({
      data: data,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Format] })
  @ApiNestedQuery(FormatFindManyArgs)
  async formats(@common.Req() request: Request): Promise<Format[]> {
    const args = plainToClass(FormatFindManyArgs, request.query);
    return this.service.formats({
      ...args,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Format })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async format(
    @common.Param() params: FormatWhereUniqueInput
  ): Promise<Format | null> {
    const result = await this.service.format({
      where: params,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Format })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFormat(
    @common.Param() params: FormatWhereUniqueInput,
    @common.Body() data: FormatUpdateInput
  ): Promise<Format | null> {
    try {
      return await this.service.updateFormat({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Format })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFormat(
    @common.Param() params: FormatWhereUniqueInput
  ): Promise<Format | null> {
    try {
      return await this.service.deleteFormat({
        where: params,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProducts(
    @common.Req() request: Request,
    @common.Param() params: FormatWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        brand: {
          select: {
            id: true,
          },
        },

        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,

        format: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  async connectProducts(
    @common.Param() params: FormatWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.updateFormat({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  async updateProducts(
    @common.Param() params: FormatWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.updateFormat({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  async disconnectProducts(
    @common.Param() params: FormatWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.updateFormat({
      where: params,
      data,
      select: { id: true },
    });
  }
}
