/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SourceService } from "../source.service";
import { SourceCreateInput } from "./SourceCreateInput";
import { Source } from "./Source";
import { SourceFindManyArgs } from "./SourceFindManyArgs";
import { SourceWhereUniqueInput } from "./SourceWhereUniqueInput";
import { SourceUpdateInput } from "./SourceUpdateInput";

export class SourceControllerBase {
  constructor(protected readonly service: SourceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Source })
  async createSource(@common.Body() data: SourceCreateInput): Promise<Source> {
    return await this.service.createSource({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Source] })
  @ApiNestedQuery(SourceFindManyArgs)
  async sources(@common.Req() request: Request): Promise<Source[]> {
    const args = plainToClass(SourceFindManyArgs, request.query);
    return this.service.sources({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Source })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async source(
    @common.Param() params: SourceWhereUniqueInput
  ): Promise<Source | null> {
    const result = await this.service.source({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Source })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSource(
    @common.Param() params: SourceWhereUniqueInput,
    @common.Body() data: SourceUpdateInput
  ): Promise<Source | null> {
    try {
      return await this.service.updateSource({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Source })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSource(
    @common.Param() params: SourceWhereUniqueInput
  ): Promise<Source | null> {
    try {
      return await this.service.deleteSource({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
